site_colors:
  CA4: '#80D8C3'
  Point C: '#932F67'
  Point D: '#D92C54'
  Point E: '#DDDEAB'
  Point F: '#4E61D3'
  Point G: '#456882'
  Site A Haute: '#F0E442'
  Site B Heugh: '#0072B2'
  Site C Chat: '#D55E00'
  Site D Simone: '#BDD4EC'
  Walde: '#4DA8DA'
  02Mn Sud Cotentin: '#FB4141'

season_color :
  spring: "green"
  summer: "orange"
  autumn: "brown"
  winter: "blue"